controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController
      ros__parameters:
        joints:
          - link1_to_base
          - link2_to_link1
          - link3_to_link2
        state_interfaces:
          - position
          - velocity
        command_interfaces:
          - position
