controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController


# Joint state broadcaster needs no params
joint_state_broadcaster:
  ros__parameters: {}


# JointGroupPositionController
position_controller:
  ros__parameters:
    joints:
      - link1_to_base
      - link2_to_link1
      - link3_to_link2
    command_interfaces:
      - position
    state_interfaces:
      - position


# ForwardCommandController (alternative)
forward_position_controller:
  ros__parameters:
    joints:
      - link1_to_base
      - link2_to_link1
      - link3_to_link2
    interface_name: position
