FKTestNode:
  ros__parameters:
    input_in_degrees: true
    step_loop: false
    num_joints: 3
    delay_seconds: 4.0
    joint_sequence_flat:
      - -15.0
      - 45.0
      - 60.0
      - 0.0
      - 45.0
      - 90.0
      - 0.0
      - 45.0
      - 120.0
      - 0.0
      - 45.0
      - 110.0
